=== ayushpatil3100/WTL/Ass3-Ass4/XML/WTL/structure.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, id, position)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT position (#PCDATA)>

=== ayushpatil3100/WTL/XML/WTL/xml-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "structure.dtd">
<employees>
    <employee>
        <name>Ayush</name>
        <id>101</id>
        <position>dev</position>
    </employee>
    <employee>
        <name>pruthvi</name>
        <id>102</id>
        <position>Developer</position>
    </employee>
</employees>
